import localFont from 'next/font/local'
import '@/styles/globals.css';


const custom = localFont({
  src: './fonts/IranianSans.ttf',
  display: 'swap',
})


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html className={custom.className} lang="en">
      <body>{children}</body>
    </html>
  )
}
